name: Submit theme
description: Submit a theme to the custom theme store!
body:
  - type: dropdown
    id: submission_type
    attributes:
      label: What is your type of submission?
      description: >
        Bundle: Modifies both the browser and websites.
        Theme: Modifies just the browser.
        Page: Modifies websites.
      options:
        - Bundle
        - Theme
        - Page
    required: true
