name: Submit theme
description: Submit a theme to the custom theme store!
title: "Add theme: "
body:
  - type: dropdown
    id: submission_type
    attributes:
      label: What is your type of submission?
      description: >
        Bundle: Modifies both the browser and websites.
        Theme: Modifies just the browser.
        Page: Modifies websites.
      options:
        - Bundle
        - Theme
        - Page
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: What is the repository's URL?
    validations:
      required: true
  - type: textarea
    id: copy_file
    attributes:
      label: What files should be copied?
      description: >
        Separate each file using new lines.
    validations:
      required: true
  - type: textarea
    id: copy_folder
    attributes:
      label: What folders should be copied?
      description: >
        Separate each folder using new lines.
    validations:
      required: true
  - type: textarea
    id: load_chrome
    attributes:
      label: What files should be loaded for the userChrome?
      description: >
        Separate each file using new lines.
    validations:
      required: true
  - type: textarea
    id: load_content
    attributes:
      label: What files should be loaded for the userContent?
      description: >
        Separate each file using new lines.
    validations:
      required: true
  - type: checkboxes
    id: copy_readme
    dropdown:
      label: Should we copy the README file?
      description: >
        If unchecked, we won't copy the repository's README file.
      options:
        - label: Yes, please copy it to the theme store.
  - type: input
    id: author
    attributes:
      label: What should we call you on the theme store?
      description: >
        If left empty, we'll use your GitHub username.
