name: Submit theme
description: Submit a theme to the custom theme store!
title: "Add theme: "
body:
  - type: input
    id: name
    attributes:
      label: What is the theme's name?
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: What is the theme's description?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What is the theme's current version?
      description: >
        If left empty, we'll use 1.0.0 as the default.
  - type: dropdown
    id: submission_type
    attributes:
      label: What is your type of submission?
      description: >
        Bundle: Modifies both the browser and websites.
        Theme: Modifies just the browser.
        Page: Modifies websites.
      options:
        - Bundle
        - Theme
        - Page
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: What is the repository's URL?
      description: >
        We'll use this to copy your files to the theme store.
    validations:
      required: true
  - type: textarea
    id: copy_file
    attributes:
      label: What files should be copied?
      description: >
        Separate each file using new lines. Leave empty if not applicable.
    validations:
      required: false
  - type: textarea
    id: copy_folder
    attributes:
      label: What folders should be copied?
      description: >
        Separate each folder using new lines. Leave empty if not applicable.
    validations:
      required: false
  - type: textarea
    id: load_chrome
    attributes:
      label: What files should be loaded for the userChrome?
      description: >
        Separate each file using new lines. Leave empty if not applicable.
    validations:
      required: false
  - type: textarea
    id: load_content
    attributes:
      label: What files should be loaded for the userContent?
      description: >
        Separate each file using new lines. Leave empty if not applicable.
    validations:
      required: false
  - type: textarea
    id: readme
    attributes:
      label: What should we put in the README?
      description: >
        Supports markdown. If left empty, we won't set a README file for your theme.
  - type: textarea
    id: domains
    attributes:
      label: What domains do your userContent file target?
      description: >
        Separate each domain using new lines. Leave empty if not applicable.
    validations:
      required: false
  - type: input
    id: author
    attributes:
      label: What should we call you on the theme store?
      description: >
        If left empty, we'll use your GitHub username.
