name: Submit theme
description: Submit a theme to the custom theme store!
title: "Add theme: "
body:
  - type: dropdown
    id: submission_type
    attributes:
      label: What is your type of submission?
      description: >
        Bundle: Modifies both the browser and websites.
        Theme: Modifies just the browser.
        Page: Modifies websites.
      options:
        - Bundle
        - Theme
        - Page
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: What should we call you on the theme store?
      description: >
        If left empty, we'll use your GitHub username.
