name: Update theme
description: Update a theme in the custom theme store!
title: "Update theme: "
body:
  - type: input
    id: id
    attributes:
      label: What is the theme's ID?
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: What is the theme's new description?
      description: >
        If left empty, we'll use the current description.
  - type: input
    id: version
    attributes:
      label: What is the theme's new version?
    validations:
      required: true
  - type: input
    id: supported
    attributes:
      label: What is the latest version of Zen Browser the theme supports?
      description: >
        e.g. 1.10.2b
    validations:
      required: true
  - type: textarea
    id: copy_file
    attributes:
      label: What files should be copied?
      description: >
        Separate each file using new lines. If left empty, we'll use the current files. Enter !erase to remove all files.
    validations:
      required: false
  - type: textarea
    id: copy_folder
    attributes:
      label: What folders should be copied?
      description: >
        Separate each file using new lines. If left empty, we'll use the current folders. Enter !erase to remove all folders.
    validations:
      required: false
  - type: textarea
    id: load_chrome
    attributes:
      label: What files should be loaded for the userChrome?
      description: >
        Separate each file using new lines. If left empty, we'll use the current files. Enter !erase to remove all files.
    validations:
      required: false
  - type: textarea
    id: load_content
    attributes:
      label: What files should be loaded for the userContent?
      description: >
        Separate each file using new lines. If left empty, we'll use the current files. Enter !erase to remove all files.
    validations:
      required: false
  - type: textarea
    id: domains
    attributes:
      label: What domains do your userContent file target?
      description: >
        e.g. google.com, youtube.com. Separate each domain using new lines. If left empty, we'll use the current domains. Enter !erase to remove all domains.
    validations:
      required: false
  - type: textarea
    id: thumbnail
    attributes:
      label: What image URL should we use for the thumbnail?
      placeholder: e.g. https://github.com/greeeen-dev/natsumi-browser/blob/main/images/main.png?raw=true
      description: >
        If left empty, we'll use the current thumbnail.
