name: Update theme
description: Update your theme in the custom theme store!
title: "Update theme: "
body:
  - type: input
    id: theme
    attributes:
      label: Theme ID
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: New version number
    validations:
      required: true
